services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - TZ=${TZ}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - COMPANY_MAP=${COMPANY_MAP}
      - SYMBOL_MAP=${SYMBOL_MAP}
      - FINNHUB_TOKEN=${FINNHUB_TOKEN}
      - ALPHAVANTAGE_API_KEY=${ALPHAVANTAGE_API_KEY}
    volumes:
      - ./data:/home/node/.n8n
    depends_on:
      - tm-scraper

  tm-scraper:
    build: .
    container_name: tm-scraper
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SCRAPY_PROJECT_ROOT=/app
      - TM_STATE_DIR=/app/.state
      - TZ=Africa/Tunis
      - COMPANY_MAP=${COMPANY_MAP}
      - SYMBOL_MAP=${SYMBOL_MAP}
      - FINNHUB_TOKEN=${FINNHUB_TOKEN}
      - ALPHAVANTAGE_API_KEY=${ALPHAVANTAGE_API_KEY}
    volumes:
      - ./out:/app/out          
      - ./state:/app/.state    
   
